### ISSUE TITLE
r2c not working suddenly

### ISSUE THREAD

**Issue by imanchatterjee** [returntocorp/cli#38] opened 2019-05-04 04:11 UTC
## To reproduce

1. Run `r2c init` or any r2c command
2. See `File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/r2c/cli/__main__.py", line 2, in <module>
    from r2c.cli.commands.build import build
  File "/usr/local/lib/python3.7/site-packages/r2c/cli/commands/build.py", line 5, in <module>
    from r2c.cli.commands.cli import cli
  File "/usr/local/lib/python3.7/site-packages/r2c/cli/commands/cli.py", line 22
    │   For non-backwards compatible changes, see |
|   getr2c.com/en/latest/troubleshooting.html │
╰─────────────────────────────────────────────╯\n"""`
3. Expect to see `...`

## Specs

- OS: [e.g. macOS Mojave, Windows 10 1809, Debian stretch]
- Python Version
- Docker Version
- Screen size (if appropriate)

**Comment by imanchatterjee** [comment] 2019-05-04 04:13
![image](https://user-images.githubusercontent.com/44714410/57173654-28735c80-6de8-11e9-9540-debbe1d80546.png)

Getting this issue for every r2c command I run

**Comment by ulziibay** [comment] 2019-05-04 04:46
Hi @imanchatterjee, 
Thanks for reporting. I am unable to reproduce with the info provided. Can you elaborate on
OS: ?
Python Version: ?
as well as the command you use right before `r2c init`.
In general, if you can provide the file in ~/.r2c/_logs/, it would me help with assisting you resolve this.

**Comment by imanchatterjee** [comment] 2019-05-04 05:19
Thank you .I think I solved the issue myself.Apparently python3 by default
was referring to Python3.5 while r2c required Python3.7 to be
accessed.Changing the symbolic link python3 to point to Python3.7 solved my
issue.
Thank you so much

**Comment by ievans** [comment] 2019-05-07 20:07
@ulziibay can we add more explicit checking when the CLI starts that the minimum python version is being used, and explain to the user if that is not the case?

**Comment by ulziibay** [comment] 2019-05-31 18:17
Python check will be released in CLI v0.0.19. Closing

**Closed by ulziibay** 2019-05-31 18:17 UTC
