### ISSUE TITLE
r2c run interactive is broken

### ISSUE THREAD

**Issue by tnarla** [returntocorp/cli#63] opened 2019-06-18 21:48 UTC
```
🔎 Inspecting containers interactively by `docker exec` into last analyzer in execution.
✘ Analyzer non-zero exit: Analyzer public/source-code:0.0.1 finished with non-zero exit code: 1.
 Container log:
 Traceback (most recent call last):
  File "/analyzer/clone.py", line 24, in <module>
    main()
  File "/analyzer/clone.py", line 17, in main
    git.Repo.clone_from(git_url, PATH_TO_OUTPUT)
  File "/usr/local/lib/python3.7/site-packages/git/repo/base.py", line 988, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/git/repo/base.py", line 939, in _clone
    finalize_process(proc, stderr=stderr)
  File "/usr/local/lib/python3.7/site-packages/git/util.py", line 333, in finalize_process
    proc.wait(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/git/cmd.py", line 415, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v v42boRXew9CctR3L /analysis/output/fs/
  stderr: 'fatal: repository 'v42boRXew9CctR3L' does not exist
'

ine@Isaacs-MBP-4 ~/D/r/p/pyre-taint [1]> r2c run -i /tmp/python/
```

**Comment by arashd** [comment] 2019-06-20 00:33
duplicate of #64

**Closed by arashd** 2019-06-20 00:33 UTC
